// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAw4lqIzjoWFJt2JUguCmFVqBz3WD1sSJ4',
    appId: '1:1017233537772:web:78b4a892429207766ac3c9',
    messagingSenderId: '1017233537772',
    projectId: 'studentswap-faae4',
    authDomain: 'studentswap-faae4.firebaseapp.com',
    storageBucket: 'studentswap-faae4.firebasestorage.app',
    measurementId: 'G-NF3G1VW3LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw4lqIzjoWFJt2JUguCmFVqBz3WD1sSJ4',
    appId: '1:1017233537772:android:6c14d971d6559ce36ac3c9',
    messagingSenderId: '1017233537772',
    projectId: 'studentswap-faae4',
    storageBucket: 'studentswap-faae4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAw4lqIzjoWFJt2JUguCmFVqBz3WD1sSJ4',
    appId: '1:1017233537772:ios:d462b174e41c165a6ac3c9',
    messagingSenderId: '1017233537772',
    projectId: 'studentswap-faae4',
    storageBucket: 'studentswap-faae4.firebasestorage.app',
    iosBundleId: 'com.example.studentswap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAw4lqIzjoWFJt2JUguCmFVqBz3WD1sSJ4',
    appId: '1:1017233537772:ios:d462b174e41c165a6ac3c9',
    messagingSenderId: '1017233537772',
    projectId: 'studentswap-faae4',
    storageBucket: 'studentswap-faae4.firebasestorage.app',
    iosBundleId: 'com.example.studentswap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAw4lqIzjoWFJt2JUguCmFVqBz3WD1sSJ4',
    appId: '1:1017233537772:web:f30312a9c0fbc0466ac3c9',
    messagingSenderId: '1017233537772',
    projectId: 'studentswap-faae4',
    authDomain: 'studentswap-faae4.firebaseapp.com',
    storageBucket: 'studentswap-faae4.firebasestorage.app',
    measurementId: 'G-4SHYSCVHZN',
  );
}
